mutation addAssetRequest($input: AddAssetRequestInputs!) {
    addAssetRequest(input: $input) {
        genesisPoint,
        name,
        metaData,
        assetId,
        outputIndex,
        proof
    }
}
