package org.royllo.explorer.core.domain.user;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import static jakarta.persistence.FetchType.EAGER;
import static jakarta.persistence.GenerationType.IDENTITY;
import static lombok.AccessLevel.PACKAGE;

/**
 * Public key generated by the user's Lightning wallet.
 * This key is unique to each user and service combination, ensuring that the user's identity is consistent with each service but not across different services.
 */
@Getter
@Setter
@ToString
@RequiredArgsConstructor
@AllArgsConstructor(access = PACKAGE)
@Builder
@Entity
@Table(name = "APPLICATION_USER_LNURL_AUTH_LINKING_KEY")
public class UserLnurlAuthKey {

    /** Unique identifier. */
    @Id
    @Column(name = "ID")
    @GeneratedValue(strategy = IDENTITY)
    private Long id;

    /** User. */
    @ManyToOne(fetch = EAGER)
    @JoinColumn(name = "FK_USER_OWNER", nullable = false)
    private User owner;

    /** Linking key. */
    @Column(name = "LINKING_KEY", nullable = false)
    private String linkingKey;

    /** K1: Randomly generated token that served as a challenge. */
    @Column(name = "K1", nullable = false)
    private String k1;

}
