package org.royllo.explorer.core.dto.user;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Value;
import org.royllo.explorer.core.domain.user.User;

import static lombok.AccessLevel.PRIVATE;

/**
 * Public key generated by the user's Lightning wallet.
 * This key is unique to each user and service combination, ensuring that the user's identity is consistent with each service but not across different services.
 */
@Value
@Builder
@AllArgsConstructor(access = PRIVATE)
public class UserLnurlAuthKeyDTO {

    /** Unique identifier. */
    Long id;

    /** Linking key owner. */
    @NotNull(message = "User owner is required")
    User owner;

    /** Linking key. */
    @NotBlank(message = "Linking key is mandatory")
    String linkingKey;

}
