# ======================================================================================================================
# The followind commands are used to download tapd and configure it.

get_and_run_tapd:
    rm -rdf tade
    git clone https://github.com/royllo/tade.git
    docker-compose -f tade/docker-compose.yml build
    docker-compose -f tade/docker-compose.yml up

retrieve_macaroon_from_tapd:
    rm -f ./src/main/resources/tapd/admin.macaroon
    sudo cp /var/lib/docker/volumes/tapd/_data/data/testnet/admin.macaroon ./src/main/resources/tapd/admin.macaroon
    sudo chown $USER ./src/main/resources/tapd/admin.macaroon

run_tapd:
    docker-compose -f tade/docker-compose.yml up

# ======================================================================================================================
# The followind commands are used to download data for each asset.

generate_roylloCoin_data:
    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/roylloCoin/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/roylloCoin/decodeProof-proofFile1-proofAtDepth0-response.json

    curl    https://mempool.space/testnet/api/tx/04feaf85babeeb5662e1139edd48b889ec178880cc69bbe38b5820dae322c75b | \
            jq > src/main/resources/mempool/04feaf85babeeb5662e1139edd48b889ec178880cc69bbe38b5820dae322c75b-response.json

    curl    https://mempool.space/testnet/api/tx/c28a42586b36ac499c6d36da792d98176572573124dbc82526d02bbad5b3d9c7 | \
            jq > src/main/resources/mempool/c28a42586b36ac499c6d36da792d98176572573124dbc82526d02bbad5b3d9c7-response.json

generate_roylloNFT_data:
    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/roylloNFT/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/roylloNFT/decodeProof-proofFile1-proofAtDepth0-response.json

    curl    https://mempool.space/testnet/api/tx/c28a42586b36ac499c6d36da792d98176572573124dbc82526d02bbad5b3d9c7 | \
            jq > src/main/resources/mempool/c28a42586b36ac499c6d36da792d98176572573124dbc82526d02bbad5b3d9c7-response.json

    curl    https://mempool.space/testnet/api/tx/6db79f5af2ba65bfb4044ced690f3acb4a791a6fc6a7450664e15559ad770b90 | \
            jq > src/main/resources/mempool/6db79f5af2ba65bfb4044ced690f3acb4a791a6fc6a7450664e15559ad770b90-response.json

generate_setOfRoylloNFT_data:
    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/setOfRoylloNFT/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/setOfRoylloNFT/decodeProof-proofFile1-proofAtDepth0-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/setOfRoylloNFT/decodeProof-proofFile2-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/setOfRoylloNFT/decodeProof-proofFile2-proofAtDepth0-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/setOfRoylloNFT/decodeProof-proofFile3-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/setOfRoylloNFT/decodeProof-proofFile3-proofAtDepth0-response.json

    curl    https://mempool.space/testnet/api/tx/6db79f5af2ba65bfb4044ced690f3acb4a791a6fc6a7450664e15559ad770b90 | \
            jq > src/main/resources/mempool/6db79f5af2ba65bfb4044ced690f3acb4a791a6fc6a7450664e15559ad770b90-response.json

    curl    https://mempool.space/testnet/api/tx/ca93a44b534f410914c18ed4563c97b0a6c31194af236d789a79683c9ec76526 | \
            jq > src/main/resources/mempool/ca93a44b534f410914c18ed4563c97b0a6c31194af236d789a79683c9ec76526-response.json

generate_trickyRoylloCoin_data:
    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/trickyRoylloCoin/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/trickyRoylloCoin/decodeProof-proofFile1-proofAtDepth0-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/trickyRoylloCoin/decodeProof-proofFile2-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/trickyRoylloCoin/decodeProof-proofFile2-proofAtDepth0-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/trickyRoylloCoin/decodeProof-proofFile2-proofAtDepth1-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/trickyRoylloCoin/decodeProof-proofFile2-proofAtDepth1-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/trickyRoylloCoin/decodeProof-proofFile3-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/trickyRoylloCoin/decodeProof-proofFile3-proofAtDepth0-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/trickyRoylloCoin/decodeProof-proofFile3-proofAtDepth1-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/trickyRoylloCoin/decodeProof-proofFile3-proofAtDepth1-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/trickyRoylloCoin/decodeProof-proofFile3-proofAtDepth2-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/trickyRoylloCoin/decodeProof-proofFile3-proofAtDepth2-response.json

    curl    https://mempool.space/testnet/api/tx/2777e306451f6d5231f4b17b8286412e1e13ef153800086cf879baae89d9df76 | \
            jq > src/main/resources/mempool/2777e306451f6d5231f4b17b8286412e1e13ef153800086cf879baae89d9df76-response.json

    curl    https://mempool.space/testnet/api/tx/632d0c3935fff230aa3718e268dce5517786d7976f7aa33efb615b408737b0ad | \
            jq > src/main/resources/mempool/632d0c3935fff230aa3718e268dce5517786d7976f7aa33efb615b408737b0ad-response.json

    curl    https://mempool.space/testnet/api/tx/f2acf1235882a7683bad5baeb1b84c2f1dbf33f0fc4a7c85f2191aa8d49ce0d3 | \
            jq > src/main/resources/mempool/f2acf1235882a7683bad5baeb1b84c2f1dbf33f0fc4a7c85f2191aa8d49ce0d3-response.json

    curl    https://mempool.space/testnet/api/tx/2727229cc771efa552f9232a04b0cd8d16df6d83bd217523888feee6a8553ec8 | \
            jq > src/main/resources/mempool/2727229cc771efa552f9232a04b0cd8d16df6d83bd217523888feee6a8553ec8-response.json

generate_unknownRoylloCoin_data:
    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/unknownRoylloCoin/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/unknownRoylloCoin/decodeProof-proofFile1-proofAtDepth0-response.json

    curl    https://mempool.space/testnet/api/tx/2727229cc771efa552f9232a04b0cd8d16df6d83bd217523888feee6a8553ec8 | \
            jq > src/main/resources/mempool/2727229cc771efa552f9232a04b0cd8d16df6d83bd217523888feee6a8553ec8-response.json

    curl    https://mempool.space/testnet/api/tx/77b550de10ad347daf314f4982a979db6d101573afe6fbf20c35935ce4bb0413 | \
            jq > src/main/resources/mempool/77b550de10ad347daf314f4982a979db6d101573afe6fbf20c35935ce4bb0413-response.json

generate_unlimitedRoylloCoin_data:
    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/unlimitedRoylloCoin/firstEmission/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/unlimitedRoylloCoin/firstEmission/decodeProof-proofFile1-proofAtDepth0-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/unlimitedRoylloCoin/secondEmission/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/unlimitedRoylloCoin/secondEmission/decodeProof-proofFile1-proofAtDepth0-response.json

    curl    https://mempool.space/testnet/api/tx/77b550de10ad347daf314f4982a979db6d101573afe6fbf20c35935ce4bb0413 | \
            jq > src/main/resources/mempool/77b550de10ad347daf314f4982a979db6d101573afe6fbf20c35935ce4bb0413-response.json

    curl    https://mempool.space/testnet/api/tx/2debb29de64ed7aafaf79c034f1ba22c41f484fafc814cab7b22a97bacfa6825 | \
            jq > src/main/resources/mempool/2debb29de64ed7aafaf79c034f1ba22c41f484fafc814cab7b22a97bacfa6825-response.json

    curl    https://mempool.space/testnet/api/tx/0516611bebe6a92675ee7360ad64edf0b3b2e967fe8c474b2d2242d5a349da3d | \
            jq > src/main/resources/mempool/0516611bebe6a92675ee7360ad64edf0b3b2e967fe8c474b2d2242d5a349da3d-response.json

    curl    https://mempool.space/testnet/api/tx/89cd5498584f217ca77d50e740e56490a710ab7b6988b3cd73aac95b9e077b1f | \
            jq > src/main/resources/mempool/89cd5498584f217ca77d50e740e56490a710ab7b6988b3cd73aac95b9e077b1f-response.json

generate_invalidProof_data:
    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/assets/invalidProof/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/assets/invalidProof/decodeProof-proofFile1-proofAtDepth0-response.json