# ======================================================================================================================
# The followind commands are used to download tapd and configure it.
get_and_run_tapd:
    rm -rdf tade
    git clone https://github.com/royllo/tade.git
    docker-compose -f tade/docker-compose.yml build
    docker-compose -f tade/docker-compose.yml up

retrieve_macaroon_from_tapd:
    rm -f ./src/main/resources/tapd/admin.macaroon
    sudo cp /var/lib/docker/volumes/tapd/_data/data/testnet/admin.macaroon ./src/main/resources/tapd/admin.macaroon
    sudo chown $USER ./src/main/resources/tapd/admin.macaroon

# ======================================================================================================================
# The followind commands are used to download data for each asset.

generate_roylloCoin_data:

generate_roylloNFT_data:

generate_setOfRoylloNFT_data:

generate_trickyRoylloCoin_data:

generate_unknownRoylloCoin_data:

generate_unlimitedRoylloCoin_data:











# ======================================================================================================================
generate_royllo_coin_data:
    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/roylloCoin/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/roylloCoin/decodeProof-proofFile1-proofAtDepth0-response.json

# ======================================================================================================================
generate_uknown_royllo_coin_data:
    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/unknownRoylloCoin/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/unknownRoylloCoin/decodeProof-proofFile1-proofAtDepth0-response.json

# ======================================================================================================================
generate_test_coin_data:
    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/testCoin/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/testCoin/decodeProof-proofFile1-proofAtDepth0-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/testCoin/decodeProof-proofFile2-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/testCoin/decodeProof-proofFile2-proofAtDepth0-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/testCoin/decodeProof-proofFile2-proofAtDepth1-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/testCoin/decodeProof-proofFile2-proofAtDepth1-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/testCoin/decodeProof-proofFile3-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/testCoin/decodeProof-proofFile3-proofAtDepth0-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/testCoin/decodeProof-proofFile3-proofAtDepth1-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/testCoin/decodeProof-proofFile3-proofAtDepth1-response.json

# ======================================================================================================================
generate_invalid_proof_data:
    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/invalid/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/invalid/decodeProof-proofFile1-proofAtDepth0-response.json

# ======================================================================================================================
generate_active_coin_data:
    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/activeRoylloCoin/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/activeRoylloCoin/decodeProof-proofFile1-proofAtDepth0-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/activeRoylloCoin/decodeProof-proofFile2-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/activeRoylloCoin/decodeProof-proofFile2-proofAtDepth0-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/activeRoylloCoin/decodeProof-proofFile2-proofAtDepth1-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/activeRoylloCoin/decodeProof-proofFile2-proofAtDepth1-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/activeRoylloCoin/decodeProof-proofFile3-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/activeRoylloCoin/decodeProof-proofFile3-proofAtDepth0-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/activeRoylloCoin/decodeProof-proofFile3-proofAtDepth1-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/activeRoylloCoin/decodeProof-proofFile3-proofAtDepth1-response.json

# ======================================================================================================================
generate_coinWithFixedSupply_data:
    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/coinWithFixedSupply/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/coinWithFixedSupply/decodeProof-proofFile1-proofAtDepth0-response.json

    curl    https://mempool.space/testnet/api/tx/ab75d04579905832c8a4ab2d6936a096496f3f0b658354324cb15594308a5e06 | \
            jq > src/main/resources/mempool/ab75d04579905832c8a4ab2d6936a096496f3f0b658354324cb15594308a5e06-response.json

    curl    https://mempool.space/testnet/api/tx/49748296309e13a71f7ed14404a66a8bb09cb6b81ec8248586d09a96e3478082 | \
            jq > src/main/resources/mempool/49748296309e13a71f7ed14404a66a8bb09cb6b81ec8248586d09a96e3478082-response.json

# ======================================================================================================================
generate_coinWithEmission_data:
    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/coinWithEmission/first/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/coinWithEmission/first/decodeProof-proofFile1-proofAtDepth0-response.json

    curl    --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./src/main/resources/tapd/admin.macaroon)" \
            --data @src/main/resources/tapd/coinWithEmission/second/decodeProof-proofFile1-proofAtDepth0-request.json \
            --insecure https://localhost:8089/v1/taproot-assets/proofs/decode | \
            jq > src/main/resources/tapd/coinWithEmission/second/decodeProof-proofFile1-proofAtDepth0-response.json

    curl    https://mempool.space/testnet/api/tx/f5cb0a137c8f5cdad6e1ba78aa34dee74b9808e33bc81b45d26d0198efd1ea95 | \
            jq > src/main/resources/mempool/f5cb0a137c8f5cdad6e1ba78aa34dee74b9808e33bc81b45d26d0198efd1ea95-response.json

    curl    https://mempool.space/testnet/api/tx/69a9ae015c9fbd947e348839efe8ae5f77fcc7b13b740ccaeadd1d664f38dae9 | \
            jq > src/main/resources/mempool/69a9ae015c9fbd947e348839efe8ae5f77fcc7b13b740ccaeadd1d664f38dae9-response.json

    curl    https://mempool.space/testnet/api/tx/21da01524e9d41f20d2fd51b76acfe0468ac0954addeb314bfd8ca63cc276a69 | \
            jq > src/main/resources/mempool/21da01524e9d41f20d2fd51b76acfe0468ac0954addeb314bfd8ca63cc276a69-response.json

    curl    https://mempool.space/testnet/api/tx/ab75d04579905832c8a4ab2d6936a096496f3f0b658354324cb15594308a5e06 | \
            jq > src/main/resources/mempool/ab75d04579905832c8a4ab2d6936a096496f3f0b658354324cb15594308a5e06-response.json

# ======================================================================================================================
generate_mempool_data:
    curl    https://mempool.space/testnet/api/tx/b97285f17dc029b92dfe0a5c9f2be412b13699fe0cf93f99deb606b20b110e75 | \
            jq > src/main/resources/mempool/b97285f17dc029b92dfe0a5c9f2be412b13699fe0cf93f99deb606b20b110e75-response.json

    curl    https://mempool.space/api/tx/46804b8a193cae200c99531f0ea90d81cc0c0e44e718b57e7b9ab5bb3926b946 | \
            jq > src/main/resources/mempool/46804b8a193cae200c99531f0ea90d81cc0c0e44e718b57e7b9ab5bb3926b946-response.json

    curl    https://mempool.space/api/tx/117ad75a79af2e7fdb2908baee9171fde4d6fb80c7322dcb895a2429f84f4d4a | \
            jq > src/main/resources/mempool/117ad75a79af2e7fdb2908baee9171fde4d6fb80c7322dcb895a2429f84f4d4a-response.json

    curl    https://mempool.space/api/tx/d61a4957e5e756a7631246b1a00d685e4854f98f8c2835bafafed8b1d1e26be5 | \
            jq > src/main/resources/mempool/d61a4957e5e756a7631246b1a00d685e4854f98f8c2835bafafed8b1d1e26be5-response.json

    curl    https://mempool.space/testnet/api/tx/d8a8016095b9fcd1f63c57342d375026ecbc72c885a54b676c6e62b216e15365 | \
            jq > src/main/resources/mempool/d8a8016095b9fcd1f63c57342d375026ecbc72c885a54b676c6e62b216e15365-response.json

    curl    https://mempool.space/testnet/api/tx/57faede9e107f3af74bb93e730bc1dfd07f81b166a974068f823d30d9eb10111 | \
            jq > src/main/resources/mempool/57faede9e107f3af74bb93e730bc1dfd07f81b166a974068f823d30d9eb10111-response.json

    curl    https://mempool.space/api/tx/2a5726687859bb1ec8a8cfeac78db8fa16b5b1c31e85be9c9812dfed68df43ea | \
            jq > src/main/resources/mempool/2a5726687859bb1ec8a8cfeac78db8fa16b5b1c31e85be9c9812dfed68df43ea-response.json

    curl    https://mempool.space/testnet/api/tx/4155275d5468dc2f116e3ea4aaddc4783a559933c7bef08fd3029fde40daf26d | \
            jq > src/main/resources/mempool/4155275d5468dc2f116e3ea4aaddc4783a559933c7bef08fd3029fde40daf26d-response.json

    curl    https://mempool.space/testnet/api/tx/cb12bb112c0211e3610300b2a93c1a2d0228b54ed49c58ca637ccb2ea0dc6f7d | \
            jq > src/main/resources/mempool/cb12bb112c0211e3610300b2a93c1a2d0228b54ed49c58ca637ccb2ea0dc6f7d-response.json

    curl    https://mempool.space/testnet/api/tx/db5c1530de5943a8f9e0f29cb2a0989cca2a3edea508dd1332d44d529e8b1408 | \
            jq > src/main/resources/mempool/db5c1530de5943a8f9e0f29cb2a0989cca2a3edea508dd1332d44d529e8b1408-response.json

    curl    https://mempool.space/testnet/api/tx/6b16776eb0a23a473b89f050fae17d07c2a4c437b0f3edaf2f0f0316f5e72d6b | \
            jq > src/main/resources/mempool/6b16776eb0a23a473b89f050fae17d07c2a4c437b0f3edaf2f0f0316f5e72d6b-response.json

# ======================================================================================================================
generate_universe_data:
    curl    https://testnet.universe.lightning.finance/v1/taproot-assets/universe/roots | \
            jq > src/main/resources/tapd/universe/universe-roots-response.json